name: Create GitHub issues from docs/issues.json

on:
  workflow_dispatch: {}

permissions:
  issues: write
  contents: read

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps (none)
        run: echo "no deps"
      - name: Create issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node .github/scripts/create_issues.js
